apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: kush  # Use your namespace name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
  spec:
    containers:
    - name: mysql
      image: mysql/mysql-server:latest
      env:
      - name: MYSQL_ROOT_PASSWORD
        value: password  # Set your MySQL root password
      ports:
      - containerPort: 3306
